"""Pydantic models for Knowledge Router.

This module defines all data models for the question-answer protocol,
routing configuration, escalation, and Q&A logging.
"""

from datetime import datetime
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

# =============================================================================
# Enums (T011)
# =============================================================================


class QuestionTarget(str, Enum):
    """Target agent type for a question."""

    ARCHITECT = "architect"
    PRODUCT = "product"
    HUMAN = "human"


class ValidationOutcome(str, Enum):
    """Outcome of answer validation."""

    ACCEPTED = "accepted"
    ESCALATE = "escalate"


class HumanAction(str, Enum):
    """Actions a human can take on an escalation."""

    CONFIRM = "confirm"
    CORRECT = "correct"
    ADD_CONTEXT = "add_context"


class AgentStatus(str, Enum):
    """Status of a dispatched agent."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    TIMEOUT = "timeout"
    CANCELLED = "cancelled"


class TaskType(str, Enum):
    """Type of execution task."""

    TEST = "test"
    IMPLEMENTATION = "implementation"
    INFRASTRUCTURE = "infrastructure"
    REVIEW = "review"


class ExecutionStatus(str, Enum):
    """Status of task execution."""

    SUCCESS = "success"
    FAILURE = "failure"
    TIMEOUT = "timeout"
    SCOPE_VIOLATION = "scope_violation"


class AgentType(str, Enum):
    """Type of agent."""

    KNOWLEDGE = "knowledge"
    EXECUTION = "execution"


# =============================================================================
# Core Q&A Models (T012-T014)
# =============================================================================


class Question(BaseModel):
    """A structured question from @baron.

    Questions are generated by the PM agent while running SpecKit commands
    and routed to knowledge agents for answers.
    """

    model_config = ConfigDict(frozen=True)

    id: str = Field(description="Unique question ID (UUID)")
    topic: Annotated[
        str,
        Field(
            min_length=2,
            max_length=50,
            pattern=r"^[a-z][a-z0-9_]*$",
            description="Question topic for routing (lowercase, alphanumeric with underscores)",
        ),
    ]
    suggested_target: QuestionTarget = Field(description="@baron's suggested target agent")
    question: Annotated[
        str,
        Field(
            min_length=10,
            max_length=2000,
            description="The question text",
        ),
    ]
    context: str = Field(
        default="",
        max_length=5000,
        description="Additional context for the question",
    )
    options: list[str] | None = Field(
        default=None,
        description="Optional answer choices",
    )
    feature_id: Annotated[
        str,
        Field(
            pattern=r"^[0-9]{3}-[a-z0-9-]+$",
            description="Feature this question belongs to (e.g., '004-knowledge-router')",
        ),
    ]
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Answer(BaseModel):
    """An agent's answer to a question.

    Answers include a confidence score (0-100) that determines whether
    the answer is accepted or escalated to human review.
    """

    model_config = ConfigDict(frozen=True)

    question_id: str = Field(description="Reference to the question")
    answered_by: Annotated[
        str,
        Field(
            pattern=r"^@?[a-z0-9][a-z0-9-]*$",
            description="Agent role or username (e.g., 'architect', '@duc', '@farmer1st')",
        ),
    ]
    answer: Annotated[
        str,
        Field(min_length=1, max_length=10000, description="The answer content"),
    ]
    rationale: Annotated[
        str,
        Field(
            min_length=20,
            max_length=5000,
            description="Why this answer is correct",
        ),
    ]
    confidence: Annotated[
        int,
        Field(ge=0, le=100, description="Confidence percentage (0-100)"),
    ]
    uncertainty_reasons: list[str] = Field(
        default_factory=list,
        description="Reasons for uncertainty (if confidence < 100)",
    )
    model_used: Annotated[
        str,
        Field(
            pattern=r"^(opus|sonnet|haiku|human)$",
            description="Model that generated this answer (or 'human' for corrections)",
        ),
    ]
    duration_seconds: Annotated[
        float,
        Field(ge=0, description="Time to generate answer"),
    ]
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def is_high_confidence(self) -> bool:
        """Check if answer meets default threshold (80%)."""
        return self.confidence >= 80


class AnswerValidationResult(BaseModel):
    """Result of validating an answer's confidence."""

    model_config = ConfigDict(frozen=True)

    outcome: ValidationOutcome
    answer: Answer
    threshold_used: int = Field(description="Confidence threshold that was applied")
    threshold_source: str = Field(
        description="Where threshold came from (default, topic_override, etc.)"
    )


# =============================================================================
# Routing Models (T015)
# =============================================================================


class RoutingRule(BaseModel):
    """Rule for routing a topic to an agent."""

    model_config = ConfigDict(frozen=True)

    topic: str = Field(description="Topic pattern (exact match)")
    agent: str = Field(description="Target agent ID or 'human'")
    confidence_threshold: int | None = Field(
        default=None,
        description="Override default threshold for this topic",
    )
    model_override: str | None = Field(
        default=None,
        description="Use specific model for this topic",
    )
    priority: int = Field(
        default=0,
        description="Higher priority rules match first",
    )


class AgentDefinition(BaseModel):
    """Definition of an agent."""

    model_config = ConfigDict(frozen=True)

    id: str = Field(description="Agent identifier (e.g., 'architect')")
    name: str = Field(description="Display name (e.g., '@duc')")
    agent_type: AgentType = Field(default=AgentType.KNOWLEDGE)
    topics: list[str] = Field(
        default_factory=list,
        description="Topics this agent handles",
    )
    scope: list[str] = Field(
        default_factory=list,
        description="File paths agent can access (execution only)",
    )
    default_model: str = Field(default="sonnet")
    default_timeout: int = Field(
        default=120,
        description="Timeout in seconds",
    )


# =============================================================================
# Agent Handle (T024)
# =============================================================================


class AgentHandle(BaseModel):
    """Handle for a dispatched agent.

    Used to track the status of an agent that has been dispatched
    to answer a question or execute a task.
    """

    model_config = ConfigDict(frozen=False)  # Status can be updated

    id: str = Field(description="Handle ID (UUID)")
    agent_role: str = Field(description="Agent role (e.g., 'architect')")
    agent_name: str = Field(description="Agent display name (e.g., '@duc')")
    status: AgentStatus = Field(default=AgentStatus.PENDING)
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = Field(default=None)
    pid: int | None = Field(default=None, description="Process ID if CLI-based")
    question_id: str | None = Field(default=None, description="Question being answered")
    task_id: str | None = Field(default=None, description="Task being executed")


# =============================================================================
# Escalation Models (T044-T045)
# =============================================================================


class EscalationRequest(BaseModel):
    """Low-confidence answer packaged for human review.

    Created when an agent's answer confidence falls below the threshold
    for the question's topic.
    """

    model_config = ConfigDict(frozen=False)  # Status can be updated

    id: str = Field(description="Escalation ID (UUID)")
    question: Question = Field(description="The original question")
    tentative_answer: Answer = Field(description="The low-confidence answer")
    threshold_used: int = Field(description="Threshold that was not met")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    github_comment_id: int | None = Field(
        default=None,
        description="GitHub comment ID where escalation was posted",
    )
    status: str = Field(
        default="pending",
        description="Status: pending, resolved, expired",
    )


class HumanResponse(BaseModel):
    """Human's response to an escalation.

    Humans can confirm the tentative answer, provide a correction,
    or add context for a re-route to the agent.
    """

    model_config = ConfigDict(frozen=True)

    escalation_id: str = Field(description="Reference to the escalation")
    action: HumanAction = Field(description="What action the human took")
    corrected_answer: str | None = Field(
        default=None,
        description="New answer if action is CORRECT",
    )
    additional_context: str | None = Field(
        default=None,
        description="Context to add if action is ADD_CONTEXT",
    )
    responder: str = Field(description="GitHub username of responder")
    github_comment_id: int = Field(description="GitHub comment ID of response")
    created_at: datetime = Field(default_factory=datetime.utcnow)


# =============================================================================
# Logging Models (T055)
# =============================================================================


class QALogEntry(BaseModel):
    """Immutable log entry for a Q&A exchange.

    Captures the complete lifecycle of a question-answer exchange,
    including any escalations and human responses.
    """

    model_config = ConfigDict(frozen=True)

    id: str = Field(description="Log entry ID (UUID)")
    feature_id: str = Field(description="Feature this exchange belongs to")
    question: Question = Field(description="The original question")
    answer: Answer = Field(description="The agent's answer")
    validation_result: AnswerValidationResult = Field(description="Result of confidence validation")
    escalation: "EscalationRequest | None" = Field(
        default=None,
        description="Escalation if answer was escalated",
    )
    human_response: HumanResponse | None = Field(
        default=None,
        description="Human response if escalated",
    )
    final_answer: Answer = Field(description="Final answer after any human intervention")
    routing_decision: str = Field(description="Which agent was chosen and why")
    total_duration_seconds: float = Field(description="Total time from question to final answer")
    parent_id: str | None = Field(
        default=None,
        description="ID of parent log entry for re-routed questions",
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
